kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tekton-resolver
  namespace: tekton-pipelines
subjects:
- kind: ServiceAccount
  name: tekton-resolver
  namespace: tekton-pipelines
roleRef:
  kind: Role
  name: tekton-resolver
  apiGroup: rbac.authorization.k8s.io
