apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogref-resolver
  namespace: tekton-pipelines
  labels:
    app.kubernetes.io/name: catalogref-resolver
    app.kubernetes.io/component: tekton-resolver
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: catalogref-resolver
      app.kubernetes.io/component: tekton-resolver
  template:
    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
      labels:
        app.kubernetes.io/name: catalogref-resolver
        app.kubernetes.io/component: tekton-resolver
        app: catalogref-resolver
    spec:
      volumes:
      - name: config-logging
        configMap:
          name: config-logging
      - name: scratch-dir
        emptyDir:
          medium: Memory
      - name: ssh-directory
        secret:
          secretName: private-catalog-key
          defaultMode: 0400
      serviceAccountName: tekton-resolver
      containers:
      - name: controller
        image: ko://github.com/tektoncd/experimental/catalogref/cmd/controller
        args:
        - "-logtostderr"
        volumeMounts:
        - name: config-logging
          mountPath: /etc/config-logging
        - name: scratch-dir
          mountPath: /tmp
        - name: ssh-directory
          mountPath: /root/.ssh
        resources:
          limits:
            # in-memory scratch-dir volume eats in to this
            memory: 256Mi
        env:
        - name: SYSTEM_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CONFIG_LOGGING_NAME
          value: config-logging
        - name: METRICS_DOMAIN
          value: tekton.dev/pipeline
        - name: CACHE_PATH
          value: /tmp
        - name: CATALOG_MAPPING
          value: |
            tekton=https://github.com/tektoncd/catalog.git
            internal=git@github.com:sbwsg/private-catalog.git
